import type { Metadata } from "next";
import { NavbarAdmin } from "@/components/ui/NavbarAdmin";
import { Footer } from "@/components/ui/Footer";

export const metadata: Metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

export default function AdminLayout({
    children,
}: Readonly<{
    children: React.ReactNode;
}>) {
    return (
        <div>
            <NavbarAdmin>
                <div className="min-h-screen flex flex-col">
                    <div className="bg-background flex-grow pt-20">
                        {children}
                    </div>
                </div>
            </NavbarAdmin>
            <Footer />
        </div>
    );
}
